initial: INIT
ok_state_package_name: stingray_missions
failed_state_package_name: stingray_missions
missions:
  INIT:
    config_name: init
    package_name: stingray_missions
  GATE:
    config_name: gate
    package_name: sauvc_missions
  BLUE_BOWL:
    config_name: blue_bowl
    package_name: sauvc_missions

transitions:
  - { source: INIT, outcome: OK, dest: GATE }
  - { source: GATE, outcome: OK, dest: BLUE_BOWL }
  - { source: BLUE_BOWL, outcome: OK, dest: OK }
