initial: DEVICE_TEST
ok_state_package_name: stingray_missions
failed_state_package_name: stingray_missions
abort_state_package_name: stingray_missions
missions:
  DEVICE_TEST:
    config_name: device_test
    package_name: sauvc_missions
transitions:
  - { source: DEVICE_TEST, outcome: OK, dest: OK }

  - { source:  DEVICE_TEST, outcome: FAILED, dest: FAILED }
