initial: INIT
ok_state_package_name: stingray_missions
failed_state_package_name: stingray_missions
abort_state_package_name: stingray_missions
missions:
  INIT:
    config_name: init
    package_name: stingray_missions
  GATE:
    config_name: gate
    package_name: sauvc_missions
  YELLOW:
    config_name: yellow_column
    package_name: sauvc_missions

transitions:
  - { source: INIT, outcome: OK, dest: GATE }
  - { source: GATE, outcome: OK, dest: YELLOW }
  - { source: YELLOW, outcome: OK, dest: OK }

  - { source: [INIT, GATE, YELLOW], outcome: FAILED, dest: FAILED }
