initial: INIT
ok_state_package_name: stingray_missions
failed_state_package_name: stingray_missions
abort_state_package_name: stingray_missions
missions:
  INIT:
    config_name: init
    package_name: stingray_missions
  SEARCH_GATE:
    config_name: search_vision_gate
    package_name: sauvc_missions
  GATE:
    config_name: gate
    package_name: sauvc_missions

transitions:
  - { source: INIT, outcome: OK, dest: SEARCH_GATE }
  - { source: SEARCH_GATE, outcome: OK, dest: GATE }
  - { source: GATE, outcome: OK, dest: OK }

  - { source: [INIT, SEARCH_GATE, GATE, END], outcome: FAILED, dest: FAILED }
