initial: INIT
ok_state_package_name: stingray_missions
failed_state_package_name: stingray_missions
abort_state_package_name: stingray_missions
missions:
  INIT:
    config_name: init
    package_name: stingray_missions
  QUALIFICATION_VISION:
    config_name: qualification_vision
    package_name: sauvc_missions
transitions:
  - { source: INIT, outcome: OK, dest: QUALIFICATION_VISION }
  - { source: QUALIFICATION_VISION, outcome: OK, dest: OK }
  - { source: [INIT, QUALIFICATION_VISION], outcome: FAILED, dest: FAILED }
