initial: INIT
ok_state_package_name: stingray_missions
failed_state_package_name: stingray_missions
abort_state_package_name: stingray_missions
missions:
  INIT:
    config_name: init
    package_name: stingray_missions
  QUALIFICATION:
    config_name: qualification
    package_name: sauvc_missions
transitions:
  - { source: INIT, outcome: OK, dest: QUALIFICATION }
  - { source: QUALIFICATION, outcome: OK, dest: OK }
  - { source: [INIT, QUALIFICATION], outcome: FAILED, dest: FAILED }
