initial: INIT
ok_state_package_name: stingray_missions
failed_state_package_name: stingray_missions
abort_state_package_name: stingray_missions
missions:
  INIT:
    config_name: init
    package_name: stingray_missions
  TEST_DAY:
    config_name: test_day
    package_name: sauvc_missions

transitions:
  - { source: INIT, outcome: OK, dest: TEST_DAY }
  - { source: TEST_DAY, outcome: OK, dest: OK }
  - { source: [INIT, TEST_DAY], outcome: FAILED, dest: FAILED }
