initial: MOVE_CENTERING_GATE
states:
  MOVE_CENTERING_GATE:
    action: 
      type: BboxCenteringTwist
      bbox_name: gate
      surge: 50.0
      depth: 500.0
      roll: 0.0
      pitch: 0.0
transitions:
  - { trigger: ok, source: MOVE_CENTERING_GATE, dest: OK }
  - { trigger: fail, source: MOVE_CENTERING_GATE, dest: FAILED }
  - { trigger: timeout, source: MOVE_CENTERING_GATE, dest: FAILED }
