initial: ENABLE_OBJECT_DETECTION
states:
  ENABLE_OBJECT_DETECTION:
    action:
      type: EnableObjectDetection
      camera_topic: /stingray/topics/front_camera
      enable: true
  MAT_CENTERING:
    action: 
      type: BboxCenteringTwist
      bbox_name: mat
      bbox_topic: /stingray/topics/front_camera/bbox_array
      distance_threshold: 5.0
      lost_threshold: 30
      avoid_bbox_name_array: []
      avoid_distance_threshold: 0.0
      avoid_horizontal_threshold: 0.0
      surge: 50.0
      sway: 0.0
      depth: 1.5
      roll: 0.0
      pitch: 0.0
      duration: 15.0
      centering_rate: 1.0
  HYDROACOUSTIC_CENTERING:
    action: 
      type: HydroacousticCenteringTwist
      bbox_name: red_bowl
      bbox_topic: /stingray/topics/front_camera/bbox_array
      hydroacoustic_topic: /stingray/topics/angle_hydroacoustic
      angle_threshold: 10.0
      distance_threshold: 2.0
      lost_threshold: 30
      surge: 50.0
      sway: 0.0
      depth: 1.5
      roll: 0.0
      pitch: 0.0
      duration: 15.0
      centering_rate: 1.5
  DISABLE_OBJECT_DETECTION:
    action:
      type: EnableObjectDetection
      camera_topic: /stingray/topics/front_camera
      enable: false
# определенное количество времени движения до тазика
# необходимо подобрать благоприятную скорость, время движения, глубину 
  MOVE_TO_BOWL: 
    action: 
      type: Twist
      surge: 50.0
      sway: 0.0
      depth: 1.5
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
      duration: 4.0
  DROPPER_OPEN:
    action:
      type: SetDeviceValue
      device: 0
      value: 1
transitions:
  - { trigger: ok, source: ENABLE_OBJECT_DETECTION, dest: MAT_CENTERING }
  - { trigger: ok, source: MAT_CENTERING, dest: HYDROACOUSTIC_CENTERING }
  - { trigger: ok, source: HYDROACOUSTIC_CENTERING, dest: DISABLE_OBJECT_DETECTION }
  - { trigger: ok, source: DISABLE_OBJECT_DETECTION, dest: MOVE_TO_BOWL }
  - { trigger: ok, source: MOVE_TO_BOWL, dest: DROPPER_OPEN }
  - { trigger: ok, source: DROPPER_OPEN, dest: OK }
