initial: SUBMERGE
states:
  SUBMERGE:
    action: 
      type: Move
      surge: 0.0
      sway: 0.0
      depth: 1.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
  MOVE_TO_GATE:
    action: 
      type: Move
      surge: 10.0
      sway: 0.0
      depth: 1.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
      duration: 5
transitions:
  - { trigger: ok, source: SUBMERGE, dest: MOVE_TO_GATE }
  - { trigger: ok, source: MOVE_TO_GATE, dest: OK }
  - { trigger: failed, source: MOVE_TO_GATE, dest: FAILED }
