initial: ENABLE_OBJECT_DETECTION
states:
  ENABLE_OBJECT_DETECTION:
    action:
      type: EnableObjectDetection
      camera_topic: /stingray/topics/front_camera
      enable: true
  MOVE_TO_GATE:
    action: 
      type: Twist
      surge: 50.0
      sway: 0.0
      depth: 500.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
      duration: 15.0
  EMERGE:
    action: 
      type: Twist
      surge: 0.0
      sway: 0.0
      depth: 50.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
      duration: 10.0
transitions:
  - { trigger: ok, source: ENABLE_OBJECT_DETECTION, dest: MOVE_TO_GATE }
  - { trigger: ok, source: MOVE_TO_GATE, dest: EMERGE }
  - { trigger: ok, source: EMERGE, dest: OK }
  - { trigger: failed, source: MOVE_TO_GATE, dest: FAILED }
