initial: QUALIFICATION
states:
  MOVE_TO GATE:
    action: 
      type: Move
      surge: 10.0
      sway: 0.0
      depth: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
transitions:
  - { trigger: ok, source: MOVE_TO_GATE, dest: OK }
  - { trigger: failed, source: MOVE_TO_GATE, dest: FAILED }
