initial: MOVE_TO_GATE
states:
  # ENABLE_OBJECT_DETECTION:
  #   action:
  #     type: EnableObjectDetection
  #     camera_topic: /stingray/topics/front_camera
  #     enable: true
  MOVE_TO_GATE:
    action: 
      type: Twist
      surge: 100.0
      sway: 0.0
      depth: 1.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
      duration: 15.0
transitions:
  # - { trigger: ok, source: ENABLE_OBJECT_DETECTION, dest: MOVE_TO_GATE }
  - { trigger: ok, source: MOVE_TO_GATE, dest: OK }
  - { trigger: fail, source: MOVE_TO_GATE, dest: FAILED }
