initial: ENABLE_OBJECT_DETECTION
states:
  ENABLE_OBJECT_DETECTION:
    action:
      type: EnableObjectDetection
      camera_topic: /stingray/topics/front_camera
      enable: true
  MOVE_WITH_CENTERING:
    action: 
      type: BboxCenteringTwist
      bbox_name: gate_qualification
      bbox_topic: /stingray/topics/front_camera/bbox_array
      distance_threshold: 1.5
      lost_threshold: 30
      avoid_bbox_name_array: []
      avoid_distance_threshold: 0.0
      avoid_horizontal_threshold: 0.0
      surge: 100.0
      sway: 0.0
      depth: 1.0
      roll: 0.0
      pitch: 0.0
      duration: 15.0
      centering_rate: 0.5
  DISABLE_OBJECT_DETECTION:
    action:
      type: EnableObjectDetection
      camera_topic: /stingray/topics/front_camera
      enable: false
transitions:
  - { trigger: ok, source: ENABLE_OBJECT_DETECTION, dest: MOVE_WITH_CENTERING }
  - { trigger: ok, source: MOVE_WITH_CENTERING, dest: DISABLE_OBJECT_DETECTION }
  - { trigger: ok, source: DISABLE_OBJECT_DETECTION, dest: OK }
