initial: ROTATE_CLOCK
states:
  ENABLE_OBJECT_DETECTION:
    action:
      type: EnableObjectDetection
      camera_topic: /stingray/topics/front_camera
      enable: true
  ROTATE_CLOCK:
    transition_event: 
      type: ObjectDetectionEvent
      topic_name: /stingray/topics/front_camera/objects
      data: gatе
      count: 5
      trigger: found
    timeout: 60
    action: 
      type: Twist
      surge: 0.0
      sway: 0.0
      depth: 500.0
      roll: 0.0
      pitch: 0.0
      yaw: 45
  ROTATE_ANTICLOCK:
    transition_event: 
      type: ObjectDetectionEvent
      topic_name: /stingray/topics/front_camera/objects
      data: gatе
      count: 5
      trigger: found
    timeout: 60
    action: 
      type: Twist
      surge: 0.0
      sway: 0.0
      depth: 500.0
      roll: 0.0
      pitch: 0.0
      yaw: -90
transitions:
  - { trigger: ok, source: ENABLE_OBJECT_DETECTION, dest: ROTATE_CLOCK }
  - { trigger: found, source: [ROTATE_CLOCK, ROTATE_ANTICLOCK], dest: OK }
  
  - { trigger: fail, source: [ENABLE_OBJECT_DETECTION, ROTATE_CLOCK, ROTATE_ANTICLOCK], dest: FAILED }
  - { trigger: timeout, source: ROTATE_CLOCK, dest: ROTATE_ANTICLOCK }
  - { trigger: timeout, source: ROTATE_ANTICLOCK, dest: FAILED }
