initial: MOVE_FORWARD
states:
  MOVE_FORWARD:
    action: 
      type: Twist
      surge: 50.0
      sway: 0.0
      depth: 1.5
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
      duration: 15.0
  MOVE_RIGHT:
    action: 
      type: Twist
      surge: 50.0
      sway: 0.0
      depth: 1.5
      roll: 0.0
      pitch: 0.0
      yaw: 90.0
      duration: 15.0
  MOVE_LEFT:
    action: 
      type: Twist
      surge: 50.0
      sway: 0.0
      depth: 1.5
      roll: 0.0
      pitch: 0.0
      yaw: -150.0
      duration: 15.0
  MOVE_BACKWARD:
    action: 
      type: Twist
      surge: 50.0
      sway: 0.0
      depth: 1.5
      roll: 0.0
      pitch: 0.0
      yaw: -150.0
      duration: 15.0
transitions:
  - { trigger: ok, source: MOVE_FORWARD, dest: MOVE_RIGHT }
  - { trigger: ok, source: MOVE_RIGHT, dest: MOVE_LEFT }
  - { trigger: ok, source: MOVE_LEFT, dest: MOVE_BACKWARD }
  - { trigger: ok, source: MOVE_BACKWARD, dest: OK }
