initial: MOVE_CENTERING_YELLOW
states:
  MOVE_CENTERING_YELLOW:
    timeout: 60
    action: 
      type: BboxCenteringTwist
      bbox_name: yellow_flare
      surge: 50.0
      depth: 500.0
      roll: 0.0
      pitch: 0.0
transitions:
  - { trigger: ok, source: MOVE_CENTERING_YELLOW, dest: OK }
  - { trigger: fail, source: MOVE_CENTERING_YELLOW, dest: FAILED }
  - { trigger: timeout, source: MOVE_CENTERING_YELLOW, dest: FAILED }
