<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sauvc_movement</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="vladik1209@gmail.com">vladushked</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>stingray_movement</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>rclcpp_components</depend>
  <depend>stingray_core_interfaces</depend>
  <depend>stingray_interfaces</depend>
  <depend>stingray_utils</depend>
  <depend>sauvc_interfaces</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
